name: happy_testing
description: A Flutter project to showcase different Flutter testing techniques.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  repository:
    path: ./packages/repository

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  mockito: 4.1.1
  test: ^1.0.0

flutter:
  uses-material-design: true
