name: repository
description: Repository project that contains the domain layer of happy testing
version: 1.0.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  api:
    path: ../api

dev_dependencies:
  mockito: 4.1.1
  test: 1.12.0